security:
    encoders:
        App\Entity\UserAccount:
            algorithm: sodium
            memory_cost: 32768
            time_cost: 50
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\UserAccount
                property: email
    
    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_OWNER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
    
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
